# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3a2064ce8c8ba95b40431f937768fc88ecb45b1d12c2a8f3d7d595e726ae27d09e0d96f67656b63efe3fe55bfe2a187405341f577297872c5015c25df995393

test:
  secret_key_base: 00d189dbf3d665ff5241e00a16726b7fd2ab5b9358dd8b22341290841295ba3bb9a60dee82b84d7669c51da0e0044a508de4b58fa0d3cd03ade3a47c32056e7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
